name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #########################
      # Build AdminService
      #########################
      - name: Build & Push AdminService Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/AdminService
          file: ./backend/AdminService/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/admin-service:latest

      #########################
      # Build CustomerService
      #########################
      - name: Build & Push CustomerService Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/CustomerService
          file: ./backend/CustomerService/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/customer-service:latest

      #########################
      # Build SellerService
      #########################
      - name: Build & Push SellerService Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/SellerService
          file: ./backend/SellerService/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/seller-service:latest

      #########################
      # Build APIGateway
      #########################
      - name: Build & Push APIGateway Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/APIGateway
          file: ./backend/APIGateway/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest

      #########################
      # Build EurekaServer
      #########################
      - name: Build & Push EurekaServer Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/EurekaServer
          file: ./backend/EurekaServer/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:latest

      #########################
      # Build Frontend
      #########################
      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
